name: Spell Check Markdown Files
 
on:
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.md'
 
jobs:
  spellcheck:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Run Markdown Spellcheck
        uses: rojopolis/spellcheck-github-actions@v0
        with:
          config_path: spellcheck.yml
          task_name: Markdown
          output_file: spellcheck-output.txt
 
      - name: Upload Spellcheck Report
        if: '!cancelled()' # Do not upload artifact if job was cancelled
        uses: actions/upload-artifact@v4
        with:
          name: spellcheck-report
          path: spellcheck-output.txt